CREATE TABLE `t_entity`
(
`b1` tinyint NULL COMMENT '',
`B2` tinyint NULL COMMENT '',
`sh3` smallint NULL COMMENT '',
`Sh4` smallint NULL COMMENT '',
`i5` integer NULL COMMENT '',
`I6` integer NULL COMMENT '',
`f7` float NULL COMMENT '',
`F8` float NULL COMMENT '',
`d9` double NULL COMMENT '',
`D10` double NULL COMMENT '',
`s11` varchar(255) NULL COMMENT '',
`test_enum` varchar (255) NULL COMMENT '',
`id` bigint (20) NOT NULL AUTO_INCREMENT COMMENT '主键',
`uuid` varchar(255) NOT NULL COMMENT '实体UUID',
`gmt_create` datetime NOT NULL COMMENT '创建时间',
`gmt_modified` datetime NOT NULL COMMENT '修改时间',
`operator_uuid` varchar(255) NULL COMMENT '操作人',
`is_delete` tinyint NULL COMMENT '是否逻辑删除, 0表示未删除，1表示已删除',
`plugin` varchar(255) NULL COMMENT '扩展信息',
`tanent_uuid` varchar(255) NULL COMMENT '租户UUID',
 PRIMARY KEY (`id`),
 KEY `idx_t_entity_uuid` (`uuid`),
 KEY `idx_t_entity_gmt_create` (`gmt_create`),
 KEY `idx_t_entity_gmt_modified` (`gmt_modified`),
 KEY `idx_t_entity_is_delete` (`is_delete`),
 KEY `idx_t_entity_tanent_uuid` (`tanent_uuid`)
) ENGINE= InnoDB DEFAULT CHARSET= utf8;


-- snailfish1.t_test_a definition

CREATE TABLE `t_test_a` (
                            `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                            `UUID` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT '实体UUID',
                            `GMT_CREATE` datetime NOT NULL COMMENT '创建时间',
                            `GMT_MODIFIED` datetime NOT NULL COMMENT '修改时间',
                            `OPERATOR_UUID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '操作人',
                            `IS_DELETE` tinyint DEFAULT NULL COMMENT '是否逻辑删除, 0表示未删除，1表示已删除',
                            `EXTENSION` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '扩展信息',
                            `TANENT_UUID` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '租户UUID',
                            `B1` tinyint DEFAULT NULL,
                            `B2` tinyint DEFAULT NULL,
                            `B2_NULL` tinyint DEFAULT NULL,
                            `SH3` smallint DEFAULT NULL,
                            `SH4` smallint DEFAULT NULL,
                            `SH4_NULL` smallint DEFAULT NULL,
                            `I5` int DEFAULT NULL,
                            `I6` int DEFAULT NULL,
                            `I6_NULL` int DEFAULT NULL,
                            `F7` float DEFAULT NULL,
                            `F8` float DEFAULT NULL,
                            `F8_NULL` float DEFAULT NULL,
                            `D9` double DEFAULT NULL,
                            `D10` double DEFAULT NULL,
                            `D10_NULL` double DEFAULT NULL,
                            `S11` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `S11_NULL` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `BY12` blob,
                            `BY12_NULL` blob,
                            `BYTE13` tinyint DEFAULT NULL,
                            `BYTE14` tinyint DEFAULT NULL,
                            `BYTE14_NULL` tinyint DEFAULT NULL,
                            `TEST_ENUM` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `TESTENUM_NULL` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `MAP` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `MAP_NULL` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `LIST` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `LIST_NULL` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `SET` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `SET_NULL` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `JSONFIELD` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            `JSONFIELD_NULL` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
                            PRIMARY KEY (`ID`),
                            KEY `idx_t_test_a_UUID` (`UUID`),
                            KEY `idx_t_test_a_GMT_CREATE` (`GMT_CREATE`),
                            KEY `idx_t_test_a_GMT_MODIFIED` (`GMT_MODIFIED`),
                            KEY `idx_t_test_a_IS_DELETE` (`IS_DELETE`),
                            KEY `idx_t_test_a_TANENT_UUID` (`TANENT_UUID`)
) ENGINE=InnoDB AUTO_INCREMENT=1234202876617773057 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;